GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/2
###

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Hemlal Dulal1",
  "title": "This is dulal note1",
  "url": "https://hemlaldulal.com1",
  "likes": 100
}

###
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "author": "Updated Author",
  "title": "Updated Title",
  "url": "https://example.com/updated-blog",
  "likes": 5
}

###
DELETE http://localhost:3001/api/blogs/3